// I define all the Action Types here //
// =================================== //


// For Dataset Reducer

export const UPDATE_TBOX = 'UPDATE_TBOX';
export const UPDATE_ABOX  = 'UPDATE_ABOX';
export const UPDATE_DATASET = 'UPDATE_DATASET';
export const UPDATE_DATASET_LIST = 'UPDATE_DATASET_LIST';
export const ADD_TO_PREFIX_LIST = 'ADD_TO_PREFIX_LIST';
export const UPDATE_DIMENSION_TREES = 'UPDATE_DIMENSION_TREES';
export const UPDATE_MEASURE_LIST = 'UPDATE_MEASURE_LIST';
export const UPDATE_SELECTED_LEVEL_DATA = 'UPDATE_SELECTED_LEVEL_DATA';
export const ADD_TO_ALL_LEVEL_DATA = 'ADD_TO_ALL_LEVEL_DATA';


// For Query Reducer

export const ADD_LEVEL = 'ADD_LEVEL';
export const REMOVE_LEVEL = 'REMOVE_LEVEL';
export const UPDATE_SELECTED_MEASURE_LIST = 'UPDATE_SELECTED_MEASURE_LIST';
export const REMOVE_MEASURE_FROM_SELECTED_MEASURE_LIST = 'REMOVE_MEASURE_FROM_SELECTED_MEASURE_LIST'
export const REMOVE_AN_AGGREGATE_FUNCTION_FROM_A_MEASURE = 'REMOVE_AN_AGGREGATE_FUNCTION_FROM_A_MEASURE'; 
export const UPDATE_LEVEL_INSTANCES = 'ADD_LEVEL_INSTANCES';
export const UPDATE_LEVEL_ATTRIBUTES_TO_VIEW_LIST = 'UPDATE_LEVEL_ATTRIBUTE_TO_VIEW_LIST';
