// I define all the Action Types here

export const UPDATE_TBOX = 'UPDATE_TBOX';
export const UPDATE_ABOX  = 'UPDATE_ABOX';
export const UPDATE_DATASET = 'UPDATE_DATASET';
export const UPDATE_DATASET_LIST = 'UPDATE_DATASET_LIST';
export const ADD_TO_PREFIX_LIST = 'ADD_TO_PREFIX_LIST';
export const UPDATE_TOTAL_NUM_OF_OBSERVATIONS = 'UPDATE_TOTAL_NUM_OF_OBSERVATIONS';
export const UPDATE_DIMENSION_TREES = 'UPDATE_DIMENSION_TREES';